---
- hosts: all
- name: Include dynamic variables
  task: 
  import_playbook: ../static-assignments/common-del.yml
  include: ../dynamic-assignments/env-vars.yml
  tags:
    - always

- hosts: webservers
- name: Webservers assignments
  import_playbook: ../static-assignments/webservers.yml
